<a href="https://colab.research.google.com/github/Text-Machine/mask-predict/blob/main/1-compute-gradients.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/> </a>

# Compute Gradients

This notebooks is prepared for computing gradients given a preformatted csv file.

Gradients compute the relation between context words and a given target word, which in our case is the token we masked, and which we want to investigate. This masked token is also referred to as the target token.

This notebooks is written for Colab but should also work on other platforms with some minor adjustments.

To measure the influence between context and target words, we need a sentences with a [MASKED] token, and a set of target tokens, for which we want to compute the gradients in the masked token position.

There are two main options strategies, and these options relate to how we model the set of target tokens

## Predictions

Here we model the relationship between contexts words and tokens predicted by a BERT model using in the fill-mask pipeline. 

### Predictions-filtered

This is a subtask, where we narrow down the set of target tokens by thematically filtering the predicted words, for example, only keep examples where BERT predicted human-like words. This filtering can happen iteratively.

## Contrastive

We provide a contrastive pair of keywords, e.g. 'machine' and 'slave' and for each senteces we compute gradients for the same pair.

In [ ]:
#!git clone https://github.com/Text-Machine/mask-predict.git

In [ ]:
#%cd mask-predict

In [ ]:
#!pip install  -q -e .

# Prepare variables and load data

In [ ]:
from explain import *
from explain.explain import MaskedLMExplainerImproved, pick_device
from collections import Counter
import pandas as pd
from pathlib import Path
import json

In [10]:
collection,genre_suffix = 'blb',''
if collection == 'blb':
  genre_suffix = '_with_genre'

maskedToken = 'machine'

modelName = "Livingwithmachines/bert_1760_1900"
dataPath = 'input_data'
processedFolder = Path('gradient_data')
processedFolder.mkdir(exist_ok=True, parents=True)
predCol = "pred_bert_1760_1900"
iloc_range = (0, -1)

In [11]:
#%cd /content

In this notebook we analyse the newspaper sentences where machine in mentioned by BLERT predicts words related to slavery.

In [12]:
#!unzip -o "{collection}_{maskedToken}_clusters{genre_suffix}_deduplicated.tsv.zip"

We rank sentences by their similarity to the 'slave' cluster based on the BLERT predictions.

In [13]:

data_df = pd.read_csv(f"./{dataPath}/{collection}_{maskedToken}_clusters{genre_suffix}_deduplicated.tsv", sep="\t", index_col=0)
data_df.head()

,record_id,date,title,author,main_publication_country,main_language,fiction_score,nonfiction_score,targetExpression,prevSentence,...,ocr_quality_mean,ocr_quality_sd,mask_index,total_masks,pred_bert_1760_1850,pred_bert_1890_1900,pred_bert_contemporary,pred_bert_1760_1900,genre,token_pseudo_ppl
0,1765210,1807,The History of England to the Revolution in 16...,"Hume, David",England,English,NaN,NaN,machine,26() HISTORY OF ENGLAND.,...,0.817,0.144,0,1,"[['tenure', 0.2492], ['service', 0.02950000000...","[['weapon', 0.21610000000000001], ['instrument...","[['force', 0.036500000000000005], ['thing', 0....","[['office', 0.12860000000000002], ['power', 0....",Non-fiction,"[('cha', 5.119544458339025), ('##p', 1.0593887..."
1,1765210,1807,The History of England to the Revolution in 16...,"Hume, David",England,English,NaN,NaN,machine,"daughter Elizabeth to John earl of Holland, an...",...,0.807,0.149,0,1,"[['armament', 0.22010000000000002], ['enterpri...","[['army', 0.1904], ['enterprise', 0.1085], ['d...","[['army', 0.5088], ['force', 0.0811], ['war', ...","[['design', 0.1492], ['confederacy', 0.1083000...",Non-fiction,"[('but', 3.2607858092947626), (',', 1.01189935..."
2,1765210,1807,The History of England to the Revolution in 16...,"Hume, David",England,English,NaN,NaN,machine,He was obliged to devolve on others the weight...,...,0.781,0.153,0,1,"[['fabric', 0.5931000000000001], ['frame', 0.2...","[['machinery', 0.3129], ['fabric', 0.257300000...","[['body', 0.0873], ['system', 0.05930000000000...","[['fabric', 0.465], ['frame', 0.1738], ['syste...",Non-fiction,"[('it', 1.0278974773610439), ('was', 1.0248746..."
3,2781218,1805,The Experienced Farmer's Tour in America: exhi...,"Parkinson, Richard",England,English,NaN,NaN,machine,"This process, the in habitants told me, would ...",...,0.826,0.150,0,1,"[['machine', 0.3522], ['method', 0.3257], ['pr...","[['process', 0.2746], ['method', 0.26], ['mach...","[['method', 0.38180000000000003], ['process', ...","[['method', 0.2989], ['machine', 0.2808], ['pr...",Non-fiction,"[('for', 44.618502713797994), (',', 2.89219029..."
4,2781219,1805,The Experienced Farmer's Tour in America: exhi...,"Parkinson, Richard",England,English,NaN,NaN,machine,"This process, the in habitants told me, would ...",...,0.720,0.178,0,1,"[['machine', 0.3522], ['method', 0.3257], ['pr...","[['process', 0.2746], ['method', 0.26], ['mach...","[['method', 0.38180000000000003], ['process', ...","[['method', 0.2989], ['machine', 0.2808], ['pr...",Non-fiction,"[('for', 44.618502713797994), (',', 2.89219029..."

In [14]:
data_df.columns

Index(['record_id', 'date', 'title', 'author', 'main_publication_country',
       'main_language', 'fiction_score', 'nonfiction_score',
       'targetExpression', 'prevSentence', 'currentSentence', 'maskedSentence',
       'nextSentence', 'pg', 'ocr_quality_mean', 'ocr_quality_sd',
       'mask_index', 'total_masks', 'pred_bert_1760_1850',
       'pred_bert_1890_1900', 'pred_bert_contemporary', 'pred_bert_1760_1900',
       'genre', 'token_pseudo_ppl'],
      dtype='str')

In [15]:
data_df.shape

(79683, 24)

In [16]:
data_df.tail(3)

,record_id,date,title,author,main_publication_country,main_language,fiction_score,nonfiction_score,targetExpression,prevSentence,...,ocr_quality_mean,ocr_quality_sd,mask_index,total_masks,pred_bert_1760_1850,pred_bert_1890_1900,pred_bert_contemporary,pred_bert_1760_1900,genre,token_pseudo_ppl
79680,2706357,1895,Cassell's Illustrated History of the Russo-Tur...,"Ollier, Edmund",England,English,NaN,NaN,machines,The four ironclads forming the Channel squadro...,...,0.692,0.173,0,1,"[['ships', 0.1168], ['vessels', 0.051800000000...","[['hours', 0.1933], ['workshops', 0.1381], ['e...","[['engineers', 0.084], ['workers', 0.0665], ['...","[['ships', 0.38670000000000004], ['vessels', 0...",Non-fiction,"[('the', 1.7322874630336995), ('artisans', 129..."
79681,3317380,1897,Ivanhoe ... With 16 illustrations by C. E. Brock,"Scott, Walter, Sir",England,English,NaN,NaN,machines,"Not so, Sir Brian,"" answered Front-de-Bœuf. """,...,0.797,0.162,0,1,"[['arms', 0.2535], ['torches', 0.0672000000000...","[['arms', 0.202], ['walls', 0.1478000000000000...","[['walls', 0.1282], ['swords', 0.0771], ['hors...","[['armour', 0.25670000000000004], ['arms', 0.1...",Non-fiction,"[('these', 10.41381169551055), ('outlaws', 602..."
79682,1913884,1890,Travels in Africa during the years 1875-1878 (...,"Junker, Wilhelm",England,English,NaN,NaN,machines,Thus the water is raised in the revolving vess...,...,0.910,0.112,0,1,"[['vessels', 0.7413000000000001], ['reservoirs...","[['vessels', 0.9684], ['jars', 0.0038], ['barg...","[['vessels', 0.7607], ['boats', 0.028800000000...","[['vessels', 0.8643000000000001], ['channels',...",Non-fiction,"[('but', 32.56057893791484), ('if', 1.27088499..."

We get all the sentences, and the top 5 predictions. This means we only look at context words where our target words of interest (like 'slave' appear in the top five words).

# Thematic filtering of the predicted target

To minimise the computation we focus on a specific sample of predictions, i.e. occurances where the MLM predicted human type words instead of machine words. 

We start with a seed list of predictions, look which other words are predicted together with these seedwords and use this expanded list as our main target of investigation.

In [17]:
texts, predicted_targets = build_texts_targets(
    data_df, start=iloc_range[0], end=iloc_range[1],
    pred_col=predCol, top_n=5
)

In [18]:
def filter_texts_targets(texts, predicted_targets, kw_filters, data_df, only_keywords=False):
    filtered_texts = []
    filtered_predicted_targets = []
    filter_identifiers = []
    for i,(text, preds) in enumerate(zip(texts, predicted_targets)):
        if set(preds).intersection(set(kw_filters)):
            filtered_texts.append(text)
            filter_identifiers.append(i)
            if only_keywords:
                preds = [p for p in preds if p in kw_filters]
                if not preds:
                    continue
            filtered_predicted_targets.append([data_df.targetExpression.iloc[i]]+preds)
    return filter_identifiers, filtered_texts, filtered_predicted_targets

In the example we first fetch human words by looking which other prediction co-occur with a set of the seed words such 'child', 'man' etc. The idea is the obtain an expanded list of words to investigate, and ensure our sample isn't completely biased by the 
We use `filter_texts_targets`, in the first round we set the  `only_keywords` argument to `False`, in the second round to `True` because we want to work only with the expanded wordlist.

In [19]:
# original keyword filters
# kw_filters = ['child', 'children', 'woman', 'man', 'women', 'men', 'father', 'mother',
#               'fathers', 'mothers','boy', 'girl','boys', 'girls','worker', 'workers', 
#               'engineer', 'engineers']
df_words = pd.read_csv(f"{dataPath}/word_human_clusters_v5_edit.csv")
kw_filters = list(df_words[df_words['human_likelihood'] > .1]['word'])
kw_filters[:4], len(kw_filters)

(['man', 'men', 'woman', 'child'], 225)

In [20]:

print('Before filtering:', len(texts), len(predicted_targets))
filter_identifiers, texts, predicted_targets = filter_texts_targets(texts, 
                                                                    predicted_targets, 
                                                                    kw_filters, data_df,
                                                                    only_keywords=True)
print('After filtering:', len(texts), len(predicted_targets))

Before filtering: 79682 79682
After filtering: 17505 17505

In [21]:
data_df.iloc[filter_identifiers].to_csv(f"{dataPath}/{collection}_{maskedToken}{genre_suffix}_pred_kw_filtered.tsv", sep="\t")

In [22]:
f"{dataPath}/{collection}_{maskedToken}{genre_suffix}_pred_kw_filtered.tsv"

'input_data/blb_machine_with_genre_pred_kw_filtered.tsv'

In [ ]:
predicted_targets[:10]

In [ ]:
# from google.colab import files
# files.download(f"{processedFolder}/{collection}_{maskedToken}{genre_suffix}_pred_kw_filtered.tsv")

In [ ]:
#open(f'{dataPath}/500_freq_pred_BL.txt','w').write('\n'.join([s for s,i in Counter([t for l in predicted_targets for t in l]).most_common(500)]))

In [ ]:
idx = 100
texts[idx],predicted_targets[idx], filter_identifiers[idx]

We run the explainer using BLERT as the model we inspect, our targets are the top 5 predictions, the texts are the 1000 sentences selected in the previous cell.

# Compute Integrated Gradients.

In [ ]:
explainer = MaskedLMExplainerImproved(model_name=modelName, device=pick_device())

In [ ]:
results = explainer.explain(texts, predicted_targets, word_agg="max")

In [ ]:
with open(f'{processedFolder}/results_{collection}_{maskedToken}_pred_kw_filtered.json', 'w') as f:
    json.dump(results, f)

In [ ]:
# with open(f'{processedFolder}/results_{collection}_{maskedToken}_pred_kw_filtered.json', 'r') as f:
#     results = json.load(f)

In [ ]:
# from google.colab import files
# files.download(f'{processedFolder}/results_{collection}_{maskedToken}_pred_kw_filtered.json')

Only retain results for context word contribution when slave or machine are predicted by BLERT.

In [ ]:
results_df = result_as_dataframe(results, kw_filters + list(data_df.targetExpression.unique()))
#results_df['identifier'] = results_df.id.apply(lambda x: filter_identifiers[int(x)])
results_df.to_csv(f'{processedFolder}/results_{collection}_{maskedToken}_pred_kw_filtered.csv')

In [ ]:
#files.download(f'results_{collection}_{maskedToken}_pred_kw_filtered.csv')

# Contrastive Analysis

Contrastive analysis, we use slave and machine as target words for all sentences, ignoring the actual predictions.

In [ ]:
if maskedToken == 'slave':
      contrastive_dict = {'slave':'machine', 'slaves':'machines'}
elif maskedToken == 'machine':
    contrastive_dict = {'machine':'slave', 'machines':'slaves'}

data_df['targetExpressionProccessed'] = data_df['targetExpression'].apply(lambda x: x.lower().strip())
data_df['targetContrExpressionProccessed'] = data_df['targetExpressionProccessed'].apply(lambda x: contrastive_dict.get(x, x))
contrastive_targets = data_df.iloc[iloc_range[0]:iloc_range[1]][['targetContrExpressionProccessed', 'targetExpressionProccessed']].values.tolist()

len(texts) == len(contrastive_targets)

In [ ]:
contrastive_targets[:3]

In [ ]:
results2 = explainer.explain(texts, contrastive_targets, word_agg="max")

In [ ]:
with open(f'results_{collection}_{maskedToken}_constrastive.json', 'w') as f:
    json.dump(results2, f)

In [ ]:
with open(f'{processedFolder}/results_{collection}_{maskedToken}_constrastive.json', 'r') as f:
    results2 = json.load(f)

In [ ]:
unique = list(set(x for sublist in contrastive_targets for x in sublist))
unique

In [ ]:
results_df = result_as_dataframe(results2,unique)
results_df.shape

In [ ]:
results_df.to_csv(f'{processedFolder}/results_{collection}_{maskedToken}_constrastive.csv')

# Fin.